# Generated by Django 6.0 on 2025-12-04 07:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('education', models.CharField(choices=[('Среднее', 'Среднее'), ('Высшее', 'Высшее'), ('Специальное', 'Специальное')], max_length=20, verbose_name='Образование')),
                ('profession', models.CharField(max_length=100, verbose_name='Профессия')),
                ('interests', models.TextField(help_text='Введите через запятую', verbose_name='Интересы')),
                ('relationship_goal', models.CharField(choices=[('Серьезные отношения', 'Серьезные отношения'), ('Дружба', 'Дружба'), ('Общение', 'Общение')], max_length=30, verbose_name='Цель знакомства')),
                ('status', models.CharField(choices=[('Холост/Не замужем', 'Холост/Не замужем'), ('В разводе', 'В разводе'), ('Вдовец/Вдова', 'Вдовец/Вдова')], max_length=20, verbose_name='Семейное положение')),
                ('avatar', models.CharField(default='👤', max_length=10, verbose_name='Аватар (эмодзи)')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Профиль виден')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dating_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to=settings.AUTH_USER_MODEL, verbose_name='От пользователя')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'ordering': ['-created_at'],
                'unique_together': {('user_from', 'user_to')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'recipient'], name='dating_mess_sender__ca212f_idx'), models.Index(fields=['-created_at'], name='dating_mess_created_0b2503_idx')],
            },
        ),
    ]
